Remove unused `Config` type
Fix the following error:
```
error[E0437]: type `Config` is not a member of trait `FromRequest`
  --> src/permissions/mod.rs:92:5
   |
92 |     type Config = ();
   |     ^^^^^^^^^^^^^^^^^ not a member of trait `FromRequest`

For more information about this error, try `rustc --explain E0437`.
error: could not compile `actix-web-grants` due to previous error
```

Signed-off-by: Mikhail Grachev <work@mgrachev.com>